// src/components/wiki/editorTextarea.svelte
<script lang="ts">
  import { EditorSettings } from './editorSettings'

  export let editable: boolean
  export let defaultValue: string

  function updateFont(e: Event) {
    const checkbox = e.target as HTMLInputElement
    EditorSettings.setKey('font', checkbox.checked ? 'mono' : 'sans')
  }
</script>

<div class="mb-2 flex gap-2">
  <label
    ><input
      type="checkbox"
      checked={$EditorSettings.font === 'mono'}
      on:change={updateFont}
    /> Use monospace font</label
  >
</div>

<textarea
  name="content"
  class={`w-full p-4 ${
    $EditorSettings.font === 'mono' ? 'font-mono' : 'font-prose'
  } text-sm rounded-xl disabled:cursor-not-allowed border-2 border-black ${
    editable ? '' : ''
  }`}
  disabled={!editable}
  rows={40}
  value={defaultValue}
/>

// src/components/wiki/editorTextarea.tsx
import { EditorSettings } from './editorSettings'
import { useStore } from '@nanostores/react'

interface EditorTextareaProps {
  editable: boolean
  defaultValue: string
}

export function EditorTextarea({
  editable,
  defaultValue,
}: EditorTextareaProps) {
  const { font } = useStore(EditorSettings)

  function updateFont(e: React.ChangeEvent<HTMLInputElement>) {
    const checkbox = e.target as HTMLInputElement
    EditorSettings.setKey('font', checkbox.checked ? 'mono' : 'sans')
  }

  return (
    <>
      <div className="mb-2 flex gap-2">
        <label>
          <input
            type="checkbox"
            checked={font === 'mono'}
            onChange={updateFont}
          />{' '}
          Use monospace font
        </label>
      </div>

      <textarea
        name="content"
        className={`w-full p-4 ${
          font === 'mono' ? 'font-mono' : 'font-prose'
        } rounded-xl border-2 border-black text-sm disabled:cursor-not-allowed ${
          editable ? '' : ''
        }`}
        disabled={!editable}
        rows={40}
        defaultValue={defaultValue}
      />
    </>
  )
}
